In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import os

In [2]:
data_path = fr'C:/ML/DataBases/airfoil_self_noise.dat'

df = pd.read_csv(data_path, sep='\t', header=None)
df

         0     1       2     3         4        5
0      800   0.0  0.3048  71.3  0.002663  126.201
1     1000   0.0  0.3048  71.3  0.002663  125.201
2     1250   0.0  0.3048  71.3  0.002663  125.951
3     1600   0.0  0.3048  71.3  0.002663  127.591
4     2000   0.0  0.3048  71.3  0.002663  127.461
...    ...   ...     ...   ...       ...      ...
1498  2500  15.6  0.1016  39.6  0.052849  110.264
1499  3150  15.6  0.1016  39.6  0.052849  109.254
1500  4000  15.6  0.1016  39.6  0.052849  106.604
1501  5000  15.6  0.1016  39.6  0.052849  106.224
1502  6300  15.6  0.1016  39.6  0.052849  104.204

[1503 rows x 6 columns]

In [3]:
df.columns = ["Frequency [Hz]", "Attack angle [deg]", "Chord length [m]", "Free-stream velocity [m/s]", "Thickness [m]", "Pressure level [db]"]

In [4]:
df

,Frequency [Hz],Attack angle [deg],Chord length [m],Free-stream velocity [m/s],Thickness [m],Pressure level [db]
0,800,0.0,0.3048,71.3,0.002663,126.201
1,1000,0.0,0.3048,71.3,0.002663,125.201
2,1250,0.0,0.3048,71.3,0.002663,125.951
3,1600,0.0,0.3048,71.3,0.002663,127.591
4,2000,0.0,0.3048,71.3,0.002663,127.461
...,...,...,...,...,...,...
1498,2500,15.6,0.1016,39.6,0.052849,110.264
1499,3150,15.6,0.1016,39.6,0.052849,109.254
1500,4000,15.6,0.1016,39.6,0.052849,106.604
1501,5000,15.6,0.1016,39.6,0.052849,106.224
1502,6300,15.6,0.1016,39.6,0.052849,104.204

In [5]:
norm_data = StandardScaler().fit_transform(df.iloc[:, :-1].to_numpy())

norm_df = pd.DataFrame(norm_data)

norm_df["Pressure level [db]"] = df.iloc[:, -1]

norm_df.columns = ["Frequency [Hz]", "Attack angle [deg]", "Chord length [m]", "Free-stream velocity [m/s]", "Thickness [m]", "Pressure level [db]"]

norm_df

,Frequency [Hz],Attack angle [deg],Chord length [m],Free-stream velocity [m/s],Thickness [m],Pressure level [db]
0,-0.662023,-1.146403,1.799299,1.312935,-0.644805,126.201
1,-0.598561,-1.146403,1.799299,1.312935,-0.644805,125.201
2,-0.519235,-1.146403,1.799299,1.312935,-0.644805,125.951
3,-0.408177,-1.146403,1.799299,1.312935,-0.644805,127.591
4,-0.281255,-1.146403,1.799299,1.312935,-0.644805,127.461
...,...,...,...,...,...,...
1498,-0.122601,1.490443,-0.373740,-0.723345,3.172773,110.264
1499,0.083648,1.490443,-0.373740,-0.723345,3.172773,109.254
1500,0.353359,1.490443,-0.373740,-0.723345,3.172773,106.604
1501,0.670666,1.490443,-0.373740,-0.723345,3.172773,106.224
1502,1.083165,1.490443,-0.373740,-0.723345,3.172773,104.204

In [6]:
x_train, x_test, y_train, y_test = train_test_split(norm_df.iloc[:, :-1], norm_df.iloc[:, -1],
                                                    shuffle=True,  random_state=42,  test_size=0.2)

In [21]:
model = ExtraTreesRegressor().fit(x_train, y_train)

In [22]:
y_pred = model.predict(x_test)

print(f'percentage corect: {model.score(x_test, y_test)}')
print(f'mse: {mean_squared_error(y_pred, y_test)}')

percentage corect: 0.951922083279063
mse: 2.4086352598940146